routes/web.php
<?php

use App\Http\Controllers\NhanSuController;
use App\Http\Controllers\VaiTroController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/nhansu');
});

Route::prefix('nhansu')->name('nhansu.')->group(function () {
    $class = NhanSuController::class;
    Route::get('/', [$class, 'index'])->name('index');
    Route::get('/create', [$class, 'create'])->name('create');
    Route::post('/', [$class, 'store'])->name('store');
    Route::get('/{nhansu}', [$class, 'show'])->name('show');
    Route::put('/{nhansu}', [$class, 'update'])->name('update');
    Route::delete('/{nhansu}', [$class, 'destroy'])->name('destroy');
    Route::get('/{nhansu}/edit', [$class, 'edit'])->name('edit');
    Route::post('/them_vt_ns', [$class, 'them_vaitro_nhansu'])->name('them_vaitro_nhansu');
    Route::get('/{nhansu}/add_vt', [$class, 'add_vai_tro_for_nhan_su'])->name('add_vai_tro_for_nhan_su');
    Route::put('/{nhansu}/luu_vt', [$class, 'luu_vai_tro_for_nhan_su'])->name('luu_vai_tro_for_nhan_su');
    Route::delete('/delete/{id}', [$class, 'delete_vaitro_of_nhansu'])->name('delete_vaitro_of_nhansu');
});

Route::prefix('vaitro')->name('vaitro.')->group(function () {
    $class = VaiTroController::class;
    Route::get('/', [$class, 'index'])->name('index');
    Route::get('/create', [$class, 'create'])->name('create');
    Route::post('/', [$class, 'store'])->name('store');
    Route::get('/{vaitro}', [$class, 'show'])->name('show');
    Route::put('/{vaitro}', [$class, 'update'])->name('update');
    Route::delete('/{vaitro}', [$class, 'destroy'])->name('destroy');
    Route::get('/{vaitro}/edit', [$class, 'edit'])->name('edit');
});

app/Models/NhanSu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class NhanSu extends Model
{
    use HasFactory;

    protected $fillable = [
        'ma_nhan_su',
        'ten_nhan_su',
        'loai_nhan_su',
        'ngay_sinh',
        'gioi_tinh',
        'SDT',
        'email',
        'dan_toc',
        'que_quan',
        'CMND',
        'trinh_do',
        'mo_ta',
    ];

    public function vai_tros()
    {
        return $this->belongsToMany(VaiTro::class, 'ns_vt', 'ma_nhan_su', 'ma_vai_tro')->withPivot('tu_ngay', 'den_ngay', 'mo_ta', 'luong_co_ban');
    }

    public function getVaiTroID($vaitros) //return 1 array cac vai tro
    {
        $getVaiTro = [];
        foreach($vaitros as $vaitro)
        {
            $getVaiTro[] = $vaitro;
        }
        return $getVaiTro;
    }

    public function saveNhanSu(Request $data)
    {
        $nhansu = $this->create([
            'ten_nhan_su' => $data['ten_nhan_su'],
            'loai_nhan_su' => $data['loai_nhan_su'],
            'ngay_sinh' => $data['ngay_sinh'],
            'gioi_tinh' => $data['gioi_tinh'],
            'SDT' => $data['SDT'],
            'email' => $data['email'],
            'dan_toc' => $data['dan_toc'],
            'que_quan' => $data['que_quan'],
            'CMND' => $data['CMND'],
            'trinh_do' => $data['trinh_do'],
            'mo_ta' => $data['mo_ta'],
        ]);

        // DB::table('ns_vt')->insert([
        //     'ma_vai_tro' => $data->ma_vai_tro,
        //     'ma_nhan_su' => $data->ma_nhan_su,
        //     'tu_ngay' => $data->tu_ngay,
        //     'den_ngay' => $data->den_ngay,
        //     'mo_ta' => $data->mo_ta,
        //     'luong_co_ban' => $data->luong_co_ban],
        // );

        // if(empty($data['vai_tros']))
        // {
        //     $vai_tros = [
        //         'Nhan vien' => '4'
        //     ];
        // }
        // else
        // {
        //     $vai_tros = $this->getVaiTroID($data['vai_tros']);
        // }

        // $nhansu->vai_tros()->attach($vai_tros);

        return $nhansu;
    }

    public function search(array $data)
    {
        $name = array_key_exists('key', $data) ? $data['key'] : null;

        return $this->SearchName($name)->latest('id')->paginate(array_key_exists('number', $data) ? $data['number'] : 10);
    }

    public function scopeSearchName($query, $name)
    {
        return $query->where('ten_nhan_su', 'like', '%' . $name . '%');
    }
}

app/Http/Controllers/NhanSuController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateNhanSuRequest;
use App\Http\Requests\CreateVaiTroForNhanSuRequest;
use App\Models\NhanSu;
use App\Models\VaiTro;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class NhanSuController extends Controller
{
    protected $nhansu;

    public function __construct(NhanSu $nhansu)
    {
        $this->nhansu = $nhansu;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $nhansu = $this->nhansu->search($request->all());
        return view('nhansu.index', compact('nhansu'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $vaitros = VaiTro::all();
        return view('nhansu.create', compact('vaitros'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateNhanSuRequest $request)
    {
        $this->nhansu->saveNhanSu($request);
        return redirect(route('nhansu.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\NhanSu  $nhansu
     * @return \Illuminate\Http\Response
     */
    public function show(NhanSu $nhansu)
    {
        return view('nhansu.show', compact('nhansu'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\NhanSu  $nhansu
     * @return \Illuminate\Http\Response
     */
    public function edit(NhanSu $nhansu)
    {
        $vt = VaiTro::all();

        $vaitros = DB::table('ns_vt')
        ->join('vai_tros', 'ns_vt.ma_vai_tro', '=', 'vai_tros.id')
        ->join('nhan_sus', 'ns_vt.ma_nhan_su', '=', 'nhan_sus.id')
        ->where('ns_vt.ma_nhan_su', '=', $nhansu->id)
        ->select('ns_vt.*', 'vai_tros.ten_vai_tro')
        ->orderBy('tu_ngay', 'DESC')
        ->get();

        return view('nhansu.edit', compact('nhansu', 'vaitros', 'vt'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\NhanSu  $nhansu
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, NhanSu $nhansu)
    {
        $nhansu->ten_nhan_su = $request->ten_nhan_su;
        $nhansu->loai_nhan_su = $request->loai_nhan_su;
        $nhansu->ngay_sinh = $request->ngay_sinh;
        $nhansu->gioi_tinh = $request->gioi_tinh;
        $nhansu->SDT = $request->SDT;
        $nhansu->email = $request->email;
        $nhansu->dan_toc = $request->dan_toc;
        $nhansu->que_quan = $request->que_quan;
        $nhansu->CMND = $request->CMND;
        $nhansu->trinh_do = $request->trinh_do;
        $nhansu->mo_ta = $request->mo_ta;
        $nhansu->save();

        // DB::table('ns_vt')->insert([
        //     'ma_nhan_su' => $request->ma_nhan_su,
        //     'ma_vai_tro' => $request->ma_vai_tro,
        //     'tu_ngay' => $request->tu_ngay,
        //     'den_ngay' => $request->den_ngay,
        //     'mo_ta' => $request->mo_ta,
        //     'luong_co_ban' => $request->luong_co_ban],
        // );

        return redirect()->back()->with('success', 'Update thành công !');
        // return redirect()->route('nhansu.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\NhanSu  $nhansu
     * @return \Illuminate\Http\Response
     */
    public function destroy(NhanSu $nhansu)
    {
        $nhansu->delete();
        return redirect()->route('nhansu.index');
    }

    public function them_vaitro_nhansu(CreateVaiTroForNhanSuRequest $request)
    {
        DB::table('ns_vt')->insert([
            'ma_vai_tro' => $request->ma_vai_tro,
            'ma_nhan_su' => $request->ma_nhan_su,
            'tu_ngay' => $request->tu_ngay,
            'den_ngay' => $request->den_ngay,
            'mo_ta' => $request->mo_ta,
            'luong_co_ban' => $request->luong_co_ban],
        );

        return redirect()->back();
        //return redirect()->back()->with('success', 'Thêm thành công!');
    }

    public function add_vai_tro_for_nhan_su(NhanSu $nhansu, Request $request)
    {
        $vaitros = VaiTro::all();
        return view ('nhansu.create_vaitro_nhansu', compact('nhansu', 'vaitros'));
    }

    public function delete_vaitro_of_nhansu(int $id)
    {
        DB::table('ns_vt')->where('id', $id)->delete();
        return redirect()->back();
        //return redirect()->back()->with('success', 'Delete thành công!');
    }
}

resources/views/nhansu/add_vai_tro.blade.php
<div class="col">
    <form action="{{ route('nhansu.them_vaitro_nhansu') }}" method="POST">
        @csrf
        <div class="form-group row">
            {{-- <label for="name" class="col-md-4 col-form-label text-md-right">Vai tro</label> --}}
            <div class="col-md-12 mt-4">
                <div class="container-fluid">
                <h4 class="text-center  @error('tu_ngay') is-invalid @enderror" style="color:green"> Them vai tro cho nhan su {{$nhansu->ten_nhan_su}} </h4>
                @error('tu_ngay')
                    <span class="invalid-feedback" role="alert">
                        <strong>Vui lòng nhập thông tin chính xác và đầy đủ</strong>
                    </span>
                @enderror
                <div class="row">
                    <div class="col-md-12">
                        <table class="table" style="background-color:#e0e0e0;" >

                            <thead>
                                <tr>
                                    <th>Ma nhan su</th>
                                    <th>Vai tro</th>
                                    <th>Tu ngay</th>
                                    <th>Den ngay</th>
                                    <th>Mo ta</th>
                                    <th>Luong co ban</th>
                                </tr>
                            </thead>
                            <tbody id="">
                                <tr>
                                    <td>
                                        <select name="ma_nhan_su" id="ma_nhan_su" class="form-select">
                                            <option id={{$nhansu->id}} value={{$nhansu->id}}>{{$nhansu->ten_nhan_su}}</option>
                                        </select>
                                    </td>
                                    <td>
                                        <select name="ma_vai_tro" id="ma_vai_tro" class="form-select">
                                            <option value="" class="vegitable custom-select">Chọn vai trò</option>
                                            @foreach($vt as $v)
                                                <option id="{{$v->id}}" value="{{$v->id}}" class="vegitable custom-select">
                                                    {{$v->ten_vai_tro}}
                                                </option>
                                            @endforeach
                                        </select>
                                    </td>
                                    <td>
                                        <input type="date" id="tu_ngay" name="tu_ngay" value="{{ old('tu_ngay') }}" class="form-control">
                                        
                                    </td>
                                    <td>
                                        <input type="date" id="den_ngay" name="den_ngay" value="{{ old('den_ngay') }}" class="form-control">
                                    </td>
                                    <td>
                                        <input type="text" id="mo_ta" name="mo_ta" value="{{ old('mo_ta') }}" class="form-control">
                                    </td>
                                    <td>
                                        <input type="number" id="luong_co_ban" name="luong_co_ban" min="0" value="{{ old('luong_co_ban') }}" class="form-control">
                                    </td>
                                    <td><button id="add" class="btn btn-success">Add</button></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <script>
            $(function(){
                $('#add').on('click',function(){

                    var ma_nhan_su = $('select[name="ma_nhan_su"]').val();
                    var ma_vai_tro = $('select[name="ma_vai_tro"]').val();
                    var tu_ngay = $('input[name="tu_ngay"]').val();
                    var den_ngay = $('input[name="den_ngay"]').val();
                    var mo_ta = $('input[name="mo_ta"]').val();
                    var luong_co_ban = $('input[name="luong_co_ban"]').val();

                    if(ma_vai_tro!="" && tu_ngay!=""){
                        $.ajax({
                            url: location.origin + 'nhansu/them_vt_ns',
                            type: "POST",
                            data: {
                                ma_nhan_su: ma_nhan_su,
                                ma_vai_tro: ma_vai_tro,
                                tu_ngay: tu_ngay,
                                den_ngay: den_ngay,
                                mo_ta: mo_ta,
                                luong_co_ban: luong_co_ban,
                            },
                        });
                        // alert('Them vai tro ' + ma_vai_tro + ' !');
                    }
                    // else{
                    //     alert('Vui lòng điền đầy đủ mã vai trò và ngày bắt đầu !');
                    // }

                    //$('#new').append('<tr><td>'+ma_vai_tro+'</td><td>'+tu_ngay+'</td><td>'+den_ngay+'</td><td>'+mo_ta+'</td><td>'+luong_co_ban+'</td><td><button class="btn btn-danger btnDelete">DELETE</button></td></tr>');
                });

                // $('.btnDelete').on('click',function(){
                //     $(this).closest("tr").remove();
                // });
            });
        </script>
    </form>
    {{-- form them / form list --}}
    <div class="col-md-12  mt-4" style="background-color:#f5f5f5;">
        <div class="p-4">
            <div class="text-center">
                <h4>Cac vai tro cua nhan su {{$nhansu->ten_nhan_su}}</h4>
            </div>
        </div>
        <table id="" class="table">
            <thead>
                <tr>
                    <th>Vai tro</th>
                    <th>Tu ngay</th>
                    <th>Den ngay</th>
                    <th>Mo ta</th>
                    <th>Luong co ban</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="new">
                @foreach ($vaitros as $vt)
                <tr>
                    <td>{{$vt->ten_vai_tro}}</td>
                    <td>{{$vt->tu_ngay}}</td>
                    <td>{{$vt->den_ngay}}</td>
                    <td>{{$vt->mo_ta}}</td>
                    <td>{{$vt->luong_co_ban}}</td>
                    <td>
                        <form action="{{ route('nhansu.delete_vaitro_of_nhansu', $vt->id) }}" method="POST" class="float-left">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btnDelete">DELETE</button>
                        </form>
                    </td>
                    {{-- <td><button class="btn btn-danger btnDelete">DELETE</button></td> --}}
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    {{-- Jquery --}}
</div>

resources/views/nhansu/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Them moi nhan su') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('nhansu.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Ten nhan su *</label>
                            <div class="col-md-6">
                                <input id="ten_nhan_su" name="ten_nhan_su" type="text" value="{{ old('ten_nhan_su') }}" class="form-control @error('ten_nhan_su') is-invalid @enderror" >
                                @error('ten_nhan_su')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Loai nhan su*</label>
                            <div class="col-md-6">
                                <div class="form-check">
                                    <input type="radio" name="loai_nhan_su" value="Nhan vien" checked>
                                    <label for="">Nhan vien</label>
                                    <input type="radio" name="loai_nhan_su" value="Ung vien">
                                    <label for="">Ung vien</label>
                                    <input type="radio" name="loai_nhan_su" value="Than nhan">
                                    <label for="">Than nhan</label>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Ngay sinh*</label>
                            <div class="col-md-6">
                                <input id="ngay_sinh" name="ngay_sinh" type="date" value="{{ old('ngay_sinh') }}" class="form-control @error('ngay_sinh') is-invalid @enderror" >
                                @error('ngay_sinh')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Gioi tinh*</label>
                            <div class="col-md-6">
                                <div class="form-check">
                                    <input type="radio" name="gioi_tinh" value="0" checked>
                                    <label for="">Nam</label>
                                    <input type="radio" name="gioi_tinh" value="1">
                                    <label for="">Nu</label>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">So dien thoai</label>
                            <div class="col-md-6">
                                <input id="SDT" name="SDT" type="tel" class="form-control" >
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Email</label>
                            <div class="col-md-6">
                                <input id="email" name="email" type="email" class="form-control" >
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Dan toc</label>
                            <div class="col-md-6">
                                <input id="dan_toc" name="dan_toc" type="text" class="form-control" >
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Que quan</label>
                            <div class="col-md-6">
                                <input id="que_quan" name="que_quan" type="text" class="form-control" >
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">CMND</label>
                            <div class="col-md-6">
                                <input id="CMND" name="CMND" type="text" class="form-control" >
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Trinh do</label>
                            <div class="col-md-6">
                                <input id="trinh_do" name="trinh_do" type="text" class="form-control" >
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Mo ta</label>
                            <div class="col-md-6">
                                <input id="mo_ta" name="mo_ta" type="text" class="form-control" >
                            </div>
                        </div>
                        <br>
                        {{-- <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Vai tro</label>
                            <div class="col-md-12">
                                @include('nhansu.create_vaitro_nhansu_partial')
                            </div>
                        </div>
                        <br> --}}
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Them
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/nhansu/create_vaitro_nhansu.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Them moi vai tro cho nhan su {{ $nhansu->ten_nhan_su }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('nhansu.luu_vai_tro_for_nhan_su', $nhansu) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="role" class="col-md-4 col-form-label text-md-right">Nhan su</label>
                            <div class="col-md-6">
                                <select name="ma_nhan_su" class="form-select form-select-sm">
                                    <option value="{{ $nhansu->id }}">{{ $nhansu->ten_nhan_su }}</option>
                                </select>
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="role" class="col-md-4 col-form-label text-md-right">Chon vai tro</label>
                            <div class="col-md-6">
                                <select name="ma_vai_tro" class="form-select form-select-sm">
                                    @foreach ($vaitros as $vaitro)
                                        <option value="{{ $vaitro->id }}">{{ $vaitro->ten_vai_tro }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Tu ngay *</label>
                            <div class="col-md-6">
                                <input id="tu_ngay" name="tu_ngay" type="text" value="{{ old('tu_ngay') }}" class="form-control @error('tu_ngay') is-invalid @enderror" >
                                @error('tu_ngay')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Den ngay</label>
                            <div class="col-md-6">
                                <input id="den_ngay" name="den_ngay" type="text" value="{{ old('den_ngay') }}" class="form-control @error('den_ngay') is-invalid @enderror" >
                                @error('den_ngay')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Mo ta</label>
                            <div class="col-md-6">
                                <input id="mo_ta" name="mo_ta" type="text" value="{{ old('mo_ta') }}" class="form-control @error('mo_ta') is-invalid @enderror" >
                                @error('mo_ta')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Luong co ban</label>
                            <div class="col-md-6">
                                <input id="luong_co_ban" name="luong_co_ban" type="text" value="{{ old('luong_co_ban') }}" class="form-control @error('luong_co_ban') is-invalid @enderror" >
                                @error('luong_co_ban')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Them
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/nhansu/partial.blade.php
{{-- @extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center"> --}}

        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">Ma vai tro</th>
                            <th scope="col">Tu ngay</th>
                            <th scope="col">Den ngay</th>
                            <th scope="col">Mo ta</th>
                            <th scope="col">Luong co ban</th>
                            <th scope="col">Actions</th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($vaitros as $vt)
                            <tr>
                                <td>{{$vt->ma_vai_tro}}</td>
                                <td>{{$vt->tu_ngay}}</td>
                                <td>{{$vt->den_ngay}}</td>
                                <td>{{$vt->mo_ta}}</td>
                                <td>{{$vt->luong_co_ban}}</td>
                                {{-- <td>
                                    <a href="{{ route('vaitro.edit', $vt->id) }}"><button type="button" class="btn btn-warning">EDIT</button>
                                    <form action="{{ route('vaitro.destroy', $vt->id) }}" method="POST" class="float-left">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">DELETE</button>
                                    </form>
                                </td> --}}
                              </tr>
                            @endforeach
                        </tbody>
                      </table>
                </div>
                <div class="card-footer">
                    <a href="{{ route('nhansu.add_vai_tro_for_nhan_su', $nhansu->id) }}" class="btn btn-primary">Them moi vai tro cho nhan su</a>
                </div>
            </div>
        </div>
    {{-- </div>
</div>
@endsection --}}