routes/web.php
<?php

use App\Http\Controllers\NhanSuController;
use App\Http\Controllers\VaiTroController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/nhansu');
});

Route::prefix('nhansu')->name('nhansu.')->group(function () {
    $class = NhanSuController::class;
    Route::get('/', [$class, 'index'])->name('index');
    Route::get('/create', [$class, 'create'])->name('create');
    Route::post('/', [$class, 'store'])->name('store');
    Route::get('/{nhansu}', [$class, 'show'])->name('show');
    Route::put('/{nhansu}', [$class, 'update'])->name('update');
    Route::delete('/{nhansu}', [$class, 'destroy'])->name('destroy');
    Route::get('/{nhansu}/edit', [$class, 'edit'])->name('edit');
    Route::post('/them_vt_ns', [$class, 'them_vaitro_nhansu'])->name('them_vaitro_nhansu');
    Route::get('/{nhansu}/add_vt', [$class, 'add_vai_tro_for_nhan_su'])->name('add_vai_tro_for_nhan_su');
    Route::put('/{nhansu}/luu_vt', [$class, 'luu_vai_tro_for_nhan_su'])->name('luu_vai_tro_for_nhan_su');
    Route::delete('/delete/{id}', [$class, 'delete_vaitro_of_nhansu'])->name('delete_vaitro_of_nhansu');
});

Route::prefix('vaitro')->name('vaitro.')->group(function () {
    $class = VaiTroController::class;
    Route::get('/', [$class, 'index'])->name('index');
    Route::get('/create', [$class, 'create'])->name('create');
    Route::post('/', [$class, 'store'])->name('store');
    Route::get('/{vaitro}', [$class, 'show'])->name('show');
    Route::put('/{vaitro}', [$class, 'update'])->name('update');
    Route::delete('/{vaitro}', [$class, 'destroy'])->name('destroy');
    Route::get('/{vaitro}/edit', [$class, 'edit'])->name('edit');
});

app/Models/VaiTro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class VaiTro extends Model
{
    use HasFactory;

    protected $fillable = [
        'ma_vai_tro',
        'ma_to_chuc',
        'ten_vai_tro',
        'mo_ta',
        'muc_luong'
    ];

    public function nhan_sus()
    {
        return $this->belongsToMany(NhanSu::class, 'ns_vt', 'ma_vai_tro', 'ma_nhan_su')->withPivot('tu_ngay', 'den_ngay', 'mo_ta', 'luong_co_ban');
    }

    public function saveVaiTro(Request $data)
    {
        $vaitro = $this->create([
            'ma_to_chuc' => $data['ma_to_chuc'],
            'ten_vai_tro' => $data['ten_vai_tro'],
            'mo_ta' => $data['mo_ta'],
            'muc_luong' => $data['muc_luong'],
        ]);

        return $vaitro;
    }

    public function search(array $data)
    {
        $name = array_key_exists('key', $data) ? $data['key'] : null;

        return $this->SearchName($name)->latest('id')->paginate(array_key_exists('number', $data) ? $data['number'] : 10);
    }

    public function scopeSearchName($query, $name)
    {
        return $query->where('ten_vai_tro', 'like', '%' . $name . '%');
    }
}

app/Http/Controllers/VaiTroController.php
<?php

namespace App\Http\Controllers;

use App\Models\ToChuc;
use App\Models\VaiTro;
use Illuminate\Http\Request;

class VaiTroController extends Controller
{
    protected $vaitro;

    public function __construct(VaiTro $vaitro)
    {
        $this->vaitro = $vaitro;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $vaitro = $this->vaitro->search($request->all());
        return view('vaitro.index', compact('vaitro'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tochucs = ToChuc::all();
        return view('vaitro.create', compact('tochucs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->vaitro->saveVaiTro($request);
        return redirect(route('vaitro.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\VaiTro  $vaiTro
     * @return \Illuminate\Http\Response
     */
    public function show(VaiTro $vaitro)
    {
        return view('vaitro.show', compact('vaitro'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\VaiTro  $vaiTro
     * @return \Illuminate\Http\Response
     */
    public function edit(VaiTro $vaitro)
    {
        $tochucs = ToChuc::all();
        return view('vaitro.edit', compact('vaitro', 'tochucs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\VaiTro  $vaiTro
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, VaiTro $vaitro)
    {
        $vaitro->ma_to_chuc = $request->ma_to_chuc;
        $vaitro->ten_vai_tro = $request->ten_vai_tro;
        $vaitro->mo_ta = $request->mo_ta;
        $vaitro->muc_luong = $request->muc_luong;
        $vaitro->save();

        return redirect()->back()->with('success', 'Update thành công !');
        //return redirect()->route('vaitro.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\VaiTro  $vaiTro
     * @return \Illuminate\Http\Response
     */
    public function destroy(VaiTro $vaitro)
    {
        $vaitro->delete();
        return redirect()->route('vaitro.index');
    }
}

resources/views/vaitro/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Them moi vai tro') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('vaitro.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Ma to chuc*</label>
                            <div class="col-md-6">
                                <select name="ma_to_chuc" id="ma_to_chuc" class="form-select">
                                    <option value="" class="vegitable custom-select">Chọn tổ chức</option>
                                    @foreach($tochucs as $tochuc)
                                        <option id="{{$tochuc->id}}" value="{{$tochuc->id}}" class="vegitable custom-select">
                                            {{$tochuc->ten_to_chuc}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <br>
                        {{-- <div class="form-group row">
                            <label for="role" class="col-md-4 col-form-label text-md-right">Select Room</label>
                            <div class="col-md-6">
                                <select name="room_id" class="form-select form-select-sm">
                                    @foreach ($rooms as $room)
                                        <option value="{{ $room->id }}">Room {{ $room->room_name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <br> --}}
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Tên vai trò*</label>
                            <div class="col-md-6">
                                <input id="ten_vai_tro" name="ten_vai_tro" type="text" value="{{ old('ten_vai_tro') }}" class="form-control @error('ten_vai_tro') is-invalid @enderror" >
                                @error('ten_vai_tro')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Mô tả</label>
                            <div class="col-md-6">
                                <input id="mo_ta" name="mo_ta" type="text" value="{{ old('mo_ta') }}" class="form-control @error('mo_ta') is-invalid @enderror" >
                                @error('mo_ta')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Mức lương</label>
                            <div class="col-md-6">
                                <input id="muc_luong" name="muc_luong" type="text" value="{{ old('muc_luong') }}" class="form-control @error('muc_luong') is-invalid @enderror" >
                                @error('muc_luong')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <br>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Them
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/vaitro/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                @if (session('success'))
                <div class="alert alert-success">
                    <p>{{ session('success') }}</p>
                </div>
                @endif

                <div class="card-header">Chinh sua vai tro {{$vaitro->id}}</div>
                <div class="card-body">
                    <form action="{{ route('vaitro.update', $vaitro) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Ma to chuc*</label>
                            <div class="col-md-6">
                                <select name="ma_to_chuc" id="ma_to_chuc" class="form-select">
                                    <option value="" class="vegitable custom-select">Chọn tổ chức</option>
                                    @foreach($tochucs as $tochuc)
                                        <option value="{{$tochuc->id}}"
                                        @if($tochuc->id == $vaitro->ma_to_chuc) selected @endif>
                                            {{$tochuc->ten_to_chuc}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Ten vai tro</label>
                            <div class="col-md-6">
                                <input id="ten_vai_tro" type="text" class="form-control" name="ten_vai_tro" value="{{ $vaitro->ten_vai_tro }}" autofocus>
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Mo ta</label>
                            <div class="col-md-6">
                                <input id="mo_ta" type="text" class="form-control" name="mo_ta" value="{{ $vaitro->mo_ta }}" autofocus>
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Muc luong</label>
                            <div class="col-md-6">
                                <input id="muc_luong" type="text" class="form-control" name="muc_luong" value="{{ $vaitro->muc_luong }}" autofocus>
                            </div>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-primary">
                            Update
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/vaitro/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">

        <div class="col-md-12">
            <h1 class="mt-4">Quan ly Vai tro</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">Welcome to Quan ly vai tro !!</li>
            </ol>
            <div class="card">
                <div class="card-header">
                    <a href="{{ route('vaitro.create') }}" class="btn btn-primary">Them moi vai tro</a>
                </div>
                <form action="{{ route('vaitro.index') }}" method="GET" class="md-3 d-flex">
                    <input type="text" class="form-control" name="key" value="{{request('key')}}">
                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
                <div class="card-body">

                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">ID</th>
                            <!-- <th scope="col">Ma to chuc</th> -->
                            <th scope="col">Ten vai tro</th>
                            <th scope="col">Mo ta</th>
                            <th scope="col">Muc luong</th>
                            <th scope="col">Actions</th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($vaitro as $vt)
                            <tr>
                                <th scope="row">{{$vt->id}}</th>
                                <!-- <td>{{$vt->ma_to_chuc}}</td> -->
                                <td>{{$vt->ten_vai_tro}}</td>
                                <td>{{$vt->mo_ta}}</td>
                                <td>{{$vt->muc_luong}}</td>
                                <td>
                                    <a href="{{ route('vaitro.show', $vt->id) }}"><button type="button" class="btn btn-success">DETAIL</button></a>
                                    <a href="{{ route('vaitro.edit', $vt->id) }}"><button type="button" class="btn btn-warning">EDIT</button>
                                    <form action="{{ route('vaitro.destroy', $vt->id) }}" method="POST" class="float-left">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">DELETE</button>
                                    </form>
                                </td>
                              </tr>
                            @endforeach
                        </tbody>
                      </table>
                      {{$vaitro->appends(request()->only('key','number'))->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/vaitro/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Vai tro thu {{$vaitro->id}}</div>

                <div class="card-body">

                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Ma to chuc</th>
                            <th scope="col">Ten vai tro</th>
                            <th scope="col">Mo ta</th>
                            <th scope="col">Muc luong</th>
                          </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">{{$vaitro->id}}</th>
                                <td>{{$vaitro->ma_to_chuc}}</td>
                                <td>{{$vaitro->ten_vai_tro}}</td>
                                <td>{{$vaitro->mo_ta}}</td>
                                <td>{{$vaitro->muc_luong}}</td>
                            </tr>
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection